import = [
    "~/.config/alacritty/colours/tokyo-night.toml"
]
live_config_reload = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 14

[shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux a -t tmux|| tmux new -s tmux"]

[env]
TERM = "xterm-256color"